# Generated by Django 4.2.1 on 2023-05-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creacurso',
            name='profesor',
            field=models.CharField(max_length=50),
        ),
    ]
